export const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL ?? 'https://srijayaenterprises.com/api/';

export const API_ENDPOINTS = {
  auth: {
    login: '/admin/auth/login',
    forgotPassword: '/admin/auth/forgot-password',
    resetPassword: '/admin/auth/reset-password',
  },
  dashboard: {
    overview: '/admin/dashboard/overview',
    inquiriesSummary: '/admin/dashboard/inquiries/summary',
    visitors: '/admin/dashboard/visitors',
  },
  home: {
    hero: '/admin/content/home/hero',
    coreServicePillars: '/admin/content/home/core-service-pillars',
    nationwidePresence: '/admin/content/home/nationwide-presence',
    nationwidePresenceSection: '/admin/content/home/nationwide-presence/section',
    nationwidePresenceStates: '/admin/content/home/nationwide-presence/states',
    nationwidePresenceLocations: '/admin/content/home/nationwide-presence/locations',
    nationwidePresenceStats: '/admin/content/home/nationwide-presence/stats',
    successStories: '/admin/content/home/success-stories',
    successStoriesSection: '/admin/content/home/success-stories/section',
    successStoriesStates: '/admin/content/home/success-stories/states',
    successStoriesStats: '/admin/content/home/success-stories/stats',
    stats: '/admin/content/home/stats',
    services: '/admin/content/home/services',
    whyChooseUs: '/admin/content/home/why-choose-us',
    machinery: '/admin/content/home/machinery',
    machineryPortfolio: '/admin/content/home/machinery-portfolio',
    machineGallery: '/admin/content/home/machinery-gallery',
    csrSection: '/admin/content/home/csr-section',
    csrInitiatives: '/admin/content/home/csr-initiatives',
    turnkeySteps: '/admin/content/home/turnkey-steps',
    productionConfigurations: '/admin/content/home/production-configurations',
    labEquipment: '/admin/content/home/lab-equipment',
    clientLogos: '/admin/content/home/client-logos',
  },
  uploads: {
    galleryImage: '/admin/uploads/gallery-image',
    brochure: '/admin/uploads/brochure',
  },
  site: {
    home: {
      machineryPortfolio: '/site/home/machinery-portfolio',
    },
  },
  about: {
    companyProfile: '/admin/content/about/company-profile',
    projects: '/admin/content/about/projects',
    certifications: '/admin/content/about/certifications',
    leadershipTeam: '/admin/content/about/leadership-team',
    companyTimeline: '/admin/content/about/company-timeline',
  },
  social: {
    csrInitiatives: '/admin/content/social/csr-initiatives',
  },
  catalog: {
    categories: '/admin/catalog/categories',
    products: '/admin/catalog/products',
  },
  labInfrastructure: {
    content: '/admin/content/catalog/lab-infrastructure',
    features: '/admin/content/catalog/lab-infrastructure/features',
    featuredProducts: '/admin/content/catalog/lab-infrastructure/featured-products',
  },
  certificationCompliance: {
    content: '/admin/content/catalog/certification-compliance',
    services: '/admin/content/catalog/certification-compliance/services',
    processSteps: '/admin/content/catalog/certification-compliance/process-steps',
    trainingPrograms: '/admin/content/catalog/certification-compliance/training-programs',
    testingGroups: '/admin/content/catalog/certification-compliance/testing-groups',
    whyChooseUsItems: '/admin/content/catalog/certification-compliance/why-choose-us-items',
  },
  industrialMachinery: {
    content: '/admin/content/catalog/industrial-machinery',
    features: '/admin/content/catalog/industrial-machinery/features',
    categories: '/admin/content/catalog/industrial-machinery/categories',
    machines: '/admin/content/catalog/industrial-machinery/machines',
    whyChooseUsItems: '/admin/content/catalog/industrial-machinery/why-choose-us-items',
    preview: '/api/site/catalog/industrial-machinery',
    previewView: '/api/site/catalog/views/industrial-machinery',
  },
  projectsPage: {
    content: '/admin/content/catalog/projects-page',
    preview: '/api/site/catalog/projects-page',
    hero: '/admin/content/catalog/projects-page/hero',
    stats: '/admin/content/catalog/projects-page/stats',
    statsReorder: '/admin/content/catalog/projects-page/stats/reorder',
    featuredSection: '/admin/content/catalog/projects-page/featured-section',
    featuredProjects: '/admin/content/catalog/projects-page/featured-projects',
    featuredProjectsReorder: '/admin/content/catalog/projects-page/featured-projects/reorder',
    featuredProjectEquipment: (projectId: string | number) =>
      `/admin/content/catalog/projects-page/featured-projects/${projectId}/equipment`,
    featuredProjectEquipmentReorder: (projectId: string | number) =>
      `/admin/content/catalog/projects-page/featured-projects/${projectId}/equipment/reorder`,
    equipment: '/admin/content/catalog/projects-page/equipment',
    calculator: '/admin/content/catalog/projects-page/calculator',
    testimonialsSection: '/admin/content/catalog/projects-page/testimonials-section',
    testimonials: '/admin/content/catalog/projects-page/testimonials',
    testimonialsReorder: '/admin/content/catalog/projects-page/testimonials/reorder',
    cta: '/admin/content/catalog/projects-page/cta',
  },
  aboutPage: {
    content: '/admin/content/catalog/about-page',
    hero: '/admin/content/catalog/about-page/hero',
    intro: '/admin/content/catalog/about-page/intro',
    mission: '/admin/content/catalog/about-page/mission',
    vision: '/admin/content/catalog/about-page/vision',
    coreValuesSection: '/admin/content/catalog/about-page/core-values-section',
    journeySection: '/admin/content/catalog/about-page/journey-section',
    certificationsSection: '/admin/content/catalog/about-page/certifications-section',
    leadershipSection: '/admin/content/catalog/about-page/leadership-section',
    whyChooseSection: '/admin/content/catalog/about-page/why-choose-section',
    cta: '/admin/content/catalog/about-page/cta',
    heroStats: '/admin/content/catalog/about-page/hero-stats',
    heroStatsReorder: '/admin/content/catalog/about-page/hero-stats/reorder',
    introGalleryImages: '/admin/content/catalog/about-page/intro-gallery-images',
    introGalleryImagesReorder: '/admin/content/catalog/about-page/intro-gallery-images/reorder',
    coreValues: '/admin/content/catalog/about-page/core-values',
    coreValuesReorder: '/admin/content/catalog/about-page/core-values/reorder',
    journeyTimeline: '/admin/content/catalog/about-page/journey-timeline',
    journeyTimelineReorder: '/admin/content/catalog/about-page/journey-timeline/reorder',
    certifications: '/admin/content/catalog/about-page/certifications',
    certificationsReorder: '/admin/content/catalog/about-page/certifications/reorder',
    leadershipMembers: '/admin/content/catalog/about-page/leadership-members',
    leadershipMembersReorder: '/admin/content/catalog/about-page/leadership-members/reorder',
    whyChooseItems: '/admin/content/catalog/about-page/why-choose-items',
    whyChooseItemsReorder: '/admin/content/catalog/about-page/why-choose-items/reorder',
  },
  contactPage: {
    content: '/admin/content/catalog/contact-page',
    hero: '/admin/content/catalog/contact-page/hero',
    contactCardsSection: '/admin/content/catalog/contact-page/contact-cards-section',
    departmentsSection: '/admin/content/catalog/contact-page/departments-section',
    formSection: '/admin/content/catalog/contact-page/form-section',
    officeSection: '/admin/content/catalog/contact-page/office-section',
    officeMap: '/admin/content/catalog/contact-page/office-map',
    contactCards: '/admin/content/catalog/contact-page/contact-cards',
    contactCardsReorder: '/admin/content/catalog/contact-page/contact-cards/reorder',
    departments: '/admin/content/catalog/contact-page/departments',
    departmentsReorder: '/admin/content/catalog/contact-page/departments/reorder',
    serviceOptions: '/admin/content/catalog/contact-page/service-options',
    serviceOptionsReorder: '/admin/content/catalog/contact-page/service-options/reorder',
    trustHighlights: '/admin/content/catalog/contact-page/trust-highlights',
    trustHighlightsReorder: '/admin/content/catalog/contact-page/trust-highlights/reorder',
    officeInfoCards: '/admin/content/catalog/contact-page/office-info-cards',
    officeInfoCardsReorder: '/admin/content/catalog/contact-page/office-info-cards/reorder',
    siteInquiries: '/site/inquiries',
    contactInquiry: '/contact/inquiry',
  },
  company: {
    contactInfo: '/admin/company/contact-info',
    callToAction: '/admin/company/call-to-action',
  },
  leads: {
    inquiries: '/admin/leads/inquiries',
    inquiryStatus: (id: string | number) => `/admin/leads/inquiries/${id}/status`,
    bulkStatus: '/admin/leads/inquiries/bulk-status',
  },
} as const;
